jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Start your app in the background and wait for it
      - name: Start app and wait for localhost:4200
        run: |
          npm run start &      # starts your server in background
          npx wait-on http://localhost:4200/login
        env:
          CI: true

      - name: Run Playwright tests (login.spec.ts only)
        run: npx playwright test tests/login.spec.ts --reporter=html

      - name: Upload Playwright HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/

      - name: Upload Playwright debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-debug-artifacts
          path: |
            test-results/
            traces/
            videos/
            screenshots/
